version: "3.7"

services:
  laravel:
    image: xoren-io-laravel
    container_name: xoren-io-laravel-testing
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
      args:
        APP_ENV: "${APP_ENV:-testing}"
        APP_USER: "${APP_USER:-laravel}"
        APP_USER_UUID: ${APP_USER_UUID:-1000}
        APP_USER_GUID: ${APP_USER_GUID:-1000}
        TZ: "${APP_TIMEZONE:-Europe/London}"
        LANG: "${APP_ENCODE:-en_GB}"
    working_dir: /var/www
    env_file: ./.env.testing
    environment:
      CONTAINER_ROLE: "laravel"
      APP_ENV: "${APP_ENV:-testing}"
      APP_USER: "${APP_USER:-laravel}"
      APP_USER_UUID: ${APP_USER_UUID:-1000}
      APP_USER_GUID: ${APP_USER_GUID:-1000}
      SWOOLE_MAX_REQUESTS:  ${SWOOLE_MAX_REQUESTS:-500}
      SWOOLE_TASK_WORKERS: ${SWOOLE_TASK_WORKERS:-auto}
      SWOOLE_WATCH: ${SWOOLE_WATCH:-false}
      SWOOLE_WORKERS: ${SWOOLE_WORKERS:-auto}
      SWOOLE_PORT: ${SWOOLE_PORT:-8000}
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
      TZ: "${APP_TIMEZONE:-Europe/London}"
      LANG: "${APP_ENCODE:-en_GB}"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - /etc/default/locale:/etc/default/locale:ro
      - /etc/locale.gen:/etc/locale.gen:ro
      - ./laravel:/var/www
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    networks:
      - DOCKER_BRIDGE

  nginx:
    image: xoren-io-nginx
    container_name: xoren-io-nginx-testing
    working_dir: /var/www
    env_file: ./.env.testing
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        TZ: "${APP_TIMEZONE:-Europe/London}"
        LANG: "${APP_ENCODE:-en_GB}"
    environment:
      TZ: "${APP_TIMEZONE:-Europe/London}"
      LANG: "${APP_ENCODE:-en_GB}"
      SWOOLE_PORT: ${SWOOLE_PORT:-8000}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - /etc/default/locale:/etc/default/locale:ro
      - /etc/locale.gen:/etc/locale.gen:ro
      - ~/pems/dhparam.pem:/etc/nginx/dhparam.pem
      - ~/pems/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key
      - ~/pems/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - ./laravel/public:/var/www/public
      - ./laravel/storage:/var/www/storage
    ports:
      - 80:80
      - 443:443
    networks:
      - DOCKER_BRIDGE

networks:
  DOCKER_BRIDGE:
    driver: bridge